# arguments for dataset
dataset: pascal
nclass: 21
crop_size: 321
data_root: Your/Pascal/Path

# arguments for training
epochs: 80
batch_size: 2 # per GPU x 4 GPUs
lr: 0.001
lr_multi: 10.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95

# arguments for model
model: deeplabv3plus
backbone: resnet101
replace_stride_with_dilation: [False, False, True]
dilations: [6, 12, 18]
